version: "3"

services:

  broker:
    image: eclipse-mosquitto

  satellite:
    build: .
    command: python satellite/satellite.py

  ground:
    build: .
    command: python ground_station/ground.py

  attacker:
    build: .
    command: python attacker/attacker.py